### ISSUE TITLE
Validations in Controller Actions Lab

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/validations-in-controller-actions-rails#3]
Validations in Controller Actions Lab is currently showing the same lesson as Validations in Controller Actions Readme with no lab to fork.

**Comment by AnnJohn** [comment]
Hi @jakebrady5 sorry about that. working on fixing it right now.

**Comment by AnnJohn** [comment]
Hi again @jakebrady5 just updated it so should be working now. thanks

**Comment by jakebrady5** [comment]
So fast! Thank you!

**Comment by AnnJohn** [comment]
you caught us at the perfect time!
