### ISSUE TITLE
positive feedback on this lab and the intro section to it

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/validations-in-controller-actions-rails#5]
I found it very helpful to have the first paragraph 'set the stage' for this lab. (pasted below):

--Now that we know Rails automatically performs validations defined on models, let's use this information to help users fix typos or other problems in their form submissions.
At this point, we'll be covering step two of the following flow:
User fills out the form and hits "Submit", transmitting the form data via a POST request.
The controller sees that validations have failed, and re-renders the form.
The view displays the errors to the user.

This is a powerful thing to set ones mind and perspective before taking in new information. 
I would love to see this type of thing as almost a default template in most lessons.  A lot of information is conveyed by 'setting the stage' like this.    

Conversely, as new concepts and especially Rails abstractions pile up at the entrance to my mind, they can sometimes lose meaning because I lack enough experience to put them in perspective. 
Little "mind roadmaps" like the one at the beginning of this lab really help to put things in perspective.  

The incredible value of Learn is that you are not only teaching us to code, but you are selectively navigating our minds through the vast materials that are available, so that we learn the most important concepts on a 'schedule', while exposing us to context and planting seeds for future learning. 

THANKS!!

**Comment by gj** [comment]
Awesome feedback @smithWEBtek, thank you! 💙
