### ISSUE TITLE
Capybara test issue

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/validations-in-controller-actions-rails#6]
in spec/views/songs/index.html.erb_spec.rb

The following test 

  it "renders a list of songs" do
    visit songs_path
    expect(all("tbody > tr").size).to eq(2)
  end

would not pass for me even though my table was being produced correctly.

I took it to AAQ. They were stumped. I'm able to get the test to pass with the following modification:
  it "renders a list of songs" do
    visit songs_path
    expect(all("tr").size).to eq(3)  #changed to three to include table header
  end

The learn expert on AAQ said I could/should raise this as an issue.

**Comment by gj** [comment]
Hi @skmcloughlin !

This is a readme — did you mean to raise the issue on a lab repo?

**Comment by skmcloughlin** [comment]
Whoops. I didn't notice it was a readme. I always work through the code either way, Sorry to bug you.

**Comment by gj** [comment]
Not bugging me at all! 🙂

I assumed you were referencing a spec file from a lab — `spec/views/songs/index.html.erb_spec.rb`. Do you remember which lab?

**Comment by skmcloughlin** [comment]
Found it in crud-with-validations-lab-v-000
